export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  TRIPS: "/trips",
  CLAIMS: "/claims",
  APPROVALS: "/approvals",
  FINANCE: "/finance",
  REPORTS: "/reports",
  HELP: "/help",
  PROFILE: "/profile",
  COMPANY_SETTINGS: {
    EMPLOYEES: "/company-settings/employees",
    CATEGORIES: "/company-settings/categories",
    ROLES_PRIVILEGES: "/company-settings/roles-privileges",
    GRADES: "/company-settings/grades",
    DEPARTMENTS: "/company-settings/departments",
    ASSOCIATED_ORGANIZATIONS: "/company-settings/associated-organizations",
  },
  EMPLOYEE_INVITE: "/company-settings/employees/invite",
  employeeEdit: (employeeId: number) => `/company-settings/employees/${employeeId}/edit`,
  REGISTER: {
    ORGANIZATION: "/register",
    DETAILS: "/register/details",
    VERIFY_EMAIL: "/register/verify-email",
    MOBILE: "/register/mobile",
    VERIFY_MOBILE: "/register/verify-mobile",
  },
  ONBOARDING: {
    VERIFY: "/onboarding",
    PROFILE: "/onboarding/profile",
    MOBILE: "/onboarding/mobile",
    VERIFY_MOBILE: "/onboarding/verify-mobile",
  },
  FORGOT_PASSWORD: {
    REQUEST: "/forgot-password",
    VERIFY: "/forgot-password/verify",
    RESET: "/forgot-password/reset",
  },
} as const;
