export type CategoryStepSegment = "basic-details" | "expense-form" | "policies" | "project-policies";

export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  TRIPS: "/trips",
  TRIP_NEW: "/trips/new",
  tripDetails: (tripId: number) => `/trips/${tripId}`,
  tripEdit: (tripId: number) => `/trips/${tripId}/edit`,
  CLAIMS: "/claims",
  CLAIM_NEW: "/claims/new",
  CLAIM_NEW_MANUAL: "/claims/new/manual",
  CLAIM_NEW_AI: "/claims/new/ai",
  claimManualEdit: (claimId: number) => `/claims/${claimId}/manual`,
  claimAiReview: (claimId: number) => `/claims/${claimId}/ai-review`,
  splitRequestDetails: (splitRequestId: number) => `/claims/split-requests/${splitRequestId}`,
  APPROVALS: "/approvals",
  FINANCE: "/finance",
  REPORTS: "/reports",
  HELP: "/help",
  PROFILE: "/profile",
  COMPANY_SETTINGS: {
    EMPLOYEES: "/company-settings/employees",
    CATEGORIES: "/company-settings/categories",
    ROLES_PRIVILEGES: "/company-settings/roles-privileges",
    GRADES: "/company-settings/grades",
    DEPARTMENTS: "/company-settings/departments",
    ASSOCIATED_ORGANIZATIONS: "/company-settings/associated-organizations",
  },
  EMPLOYEE_INVITE: "/company-settings/employees/invite",
  EMPLOYEE_BULK_INVITE: "/company-settings/employees/bulk-invite",
  employeeEdit: (employeeId: number) => `/company-settings/employees/${employeeId}/edit`,
  CATEGORY_NEW: "/company-settings/categories/new",
  categoryDetails: (categoryId: number) => `/company-settings/categories/${categoryId}`,
  categoryStep: (categoryId: number, step: CategoryStepSegment) => `/company-settings/categories/${categoryId}/${step}`,
  REGISTER: {
    ORGANIZATION: "/register",
    DETAILS: "/register/details",
    VERIFY_EMAIL: "/register/verify-email",
    MOBILE: "/register/mobile",
    VERIFY_MOBILE: "/register/verify-mobile",
  },
  ONBOARDING: {
    VERIFY: "/onboarding",
    PROFILE: "/onboarding/profile",
    MOBILE: "/onboarding/mobile",
    VERIFY_MOBILE: "/onboarding/verify-mobile",
  },
  FORGOT_PASSWORD: {
    REQUEST: "/forgot-password",
    VERIFY: "/forgot-password/verify",
    RESET: "/forgot-password/reset",
  },
} as const;
