export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  TRIPS: "/trips",
  CLAIMS: "/claims",
  APPROVALS: "/approvals",
  FINANCE: "/finance",
  REPORTS: "/reports",
  HELP: "/help",
  PROFILE: "/profile",
  COMPANY_SETTINGS: {
    EMPLOYEES: "/company-settings/employees",
    CATEGORIES: "/company-settings/categories",
    ROLES_PRIVILEGES: "/company-settings/roles-privileges",
    GRADES: "/company-settings/grades",
    DEPARTMENTS: "/company-settings/departments",
    ORGANIZATIONS: "/company-settings/organizations",
    ASSOCIATED_ORGANIZATIONS: "/company-settings/associated-organizations",
  },
  EMPLOYEE_INVITE: {
    BASIC_INFO: "/company-settings/employees/invite",
    COMPANY_ACCESS: "/company-settings/employees/invite/company-access",
    FF_NUMBERS: "/company-settings/employees/invite/ff-numbers",
    ACCESS_APPROVAL: "/company-settings/employees/invite/access-approval",
  },
  REGISTER: {
    ORGANIZATION: "/register",
    DETAILS: "/register/details",
    VERIFY_EMAIL: "/register/verify-email",
    MOBILE: "/register/mobile",
    VERIFY_MOBILE: "/register/verify-mobile",
  },
  FORGOT_PASSWORD: {
    REQUEST: "/forgot-password",
    VERIFY: "/forgot-password/verify",
    RESET: "/forgot-password/reset",
  },
} as const;
