/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A set of two or more files with an identical content hash. */
export interface DuplicateGroup {
  hash: string
  files: Array<ScannedFile>
}

/**
 * Phase 3 milestone: the smallest possible proof that the main process can
 * call into Rust and get a typed result back. Every later Rust feature
 * (e.g. Phase 4's receipt-folder hashing below) reuses this exact main ->
 * preload -> renderer wiring, just with a different function here.
 */
export declare function ping(name: string): string

/**
 * Phase 4: give Rust a real job. Walks `root`, content-hashes every file
 * with BLAKE3, and reports duplicates + totals — the check a receipt folder
 * deserves before its files are uploaded to claim-service (Phase 10), and
 * genuinely CPU-bound work over many files, which is where Rust earns its
 * place over doing the same walk in Node.
 */
export declare function scanFolder(root: string): ScanResult

/** One file found during a folder scan, identified by its content hash. */
export interface ScannedFile {
  path: string
  name: string
  /**
   * Bytes. `f64` (not `u64`/`i64`) because napi maps integer fields to a
   * plain JS `number`, which loses precision above 2^53 — irrelevant for
   * receipt-sized files, and avoids forcing BigInt on the TS side.
   */
  size: number
  hash: string
}

export interface ScanResult {
  root: string
  totalFiles: number
  totalSize: number
  duplicateFileCount: number
  duplicateGroups: Array<DuplicateGroup>
}
