/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Looks up a cached GET response by its full request path+querystring.
 * Returns the raw JSON string previously stored by `cachePut`, or `None`.
 */
export declare function cacheGet(key: string): string | null

/**
 * Drops every cache row whose path starts with `prefix` — used after a
 * write to invalidate stale list/detail responses for that same resource.
 */
export declare function cacheInvalidatePrefix(prefix: string): void

/** Write-through cache upsert, called after every successful GET. */
export declare function cachePut(key: string, path: string, data: string, updatedAt: number): void

/** A set of two or more files with an identical content hash. */
export interface DuplicateGroup {
  hash: string
  files: Array<ScannedFile>
}

/**
 * Enqueues a write made while offline. `local_id` is set only for a
 * "create" (the negative ID allocated via `nextLocalId`); every other write
 * (update/delete/status-change) passes `None`.
 */
export declare function enqueueOperation(method: string, path: string, body: string | undefined | null, localId: number | undefined | null, createdAt: number): number

export declare function getPendingCount(): number

/**
 * Opens (or creates) the local SQLite DB at `path` and applies the schema.
 * `path` is computed in Node from `app.getPath("userData")`, since Rust has
 * no notion of Electron's per-OS data directories. Must be called exactly
 * once, before any other function in this module.
 */
export declare function initDb(path: string): void

/**
 * Operations ready to replay, in strict creation order (the autoincrement
 * rowid, not `created_at` — a millisecond timestamp can tie under rapid
 * successive writes, the rowid never does).
 */
export declare function listPendingOperations(): Array<PendingOperation>

/**
 * Operations that will never be retried by `runSync` on their own and need
 * an explicit user decision: `syncing` rows left over from a previous run
 * that never confirmed success or failure (almost always an app crash/
 * force-quit mid-request — the server may already have received them, so
 * silently retrying risks a duplicate record), and `failed` rows (the sync
 * engine stops the whole queue on the first real failure — e.g. a genuine
 * 404 for something already deleted server-side by someone else — so a
 * permanently-failing operation would otherwise jam every later queued
 * write behind it forever with no way to clear it).
 */
export declare function listStuckOperations(): Array<PendingOperation>

export declare function markOperationFailed(id: number, error: string): void

/**
 * Marks a row as in-flight, committed *before* the request is sent — the
 * half of the crash-safety design that makes a `syncing` row on next launch
 * mean "may have already reached the server", not "definitely didn't".
 */
export declare function markOperationSyncing(id: number): void

/**
 * Allocates the next negative local ID for an offline "create" (-1, -2, ...).
 * Persisted in `kv_meta` rather than derived from `MIN(local_id)`, so it
 * keeps counting down correctly even after old rows are removed on sync.
 */
export declare function nextLocalId(): number

/** One queued write, as returned to the main process's sync engine. */
export interface PendingOperation {
  id: number
  localId?: number
  method: string
  path: string
  body?: string
  createdAt: number
  status: string
  retryCount: number
  lastError?: string
}

/**
 * Phase 3 milestone: the smallest possible proof that the main process can
 * call into Rust and get a typed result back. Every later Rust feature
 * (e.g. Phase 4's receipt-folder hashing below) reuses this exact main ->
 * preload -> renderer wiring, just with a different function here.
 */
export declare function ping(name: string): string

/**
 * Called once a queued "create" syncs and the server hands back a real ID:
 * rewrites every *other* still-pending/failed operation's path and body so
 * anything referencing the old negative ID (same-entity chaining, e.g.
 * edit-after-create, or a cross-domain FK, e.g. a claim referencing a
 * locally-created trip) picks up the real one before it gets replayed.
 */
export declare function remapNegativeId(oldId: number, newId: number): void

/**
 * Removes a row after it's been confirmed synced — the queue only ever
 * holds work still to do; the cache table is the durable record afterward.
 */
export declare function removeOperation(id: number): void

/**
 * User's explicit answer to a stuck (crashed-mid-sync) operation: `retry`
 * puts it back in the normal queue; otherwise it's discarded outright.
 */
export declare function resolveStuckOperation(id: number, retry: boolean): void

/**
 * Phase 4: give Rust a real job. Walks `root`, content-hashes every file
 * with BLAKE3, and reports duplicates + totals — the check a receipt folder
 * deserves before its files are uploaded to claim-service (Phase 10), and
 * genuinely CPU-bound work over many files, which is where Rust earns its
 * place over doing the same walk in Node.
 */
export declare function scanFolder(root: string): ScanResult

/** One file found during a folder scan, identified by its content hash. */
export interface ScannedFile {
  path: string
  name: string
  /**
   * Bytes. `f64` (not `u64`/`i64`) because napi maps integer fields to a
   * plain JS `number`, which loses precision above 2^53 — irrelevant for
   * receipt-sized files, and avoids forcing BigInt on the TS side.
   */
  size: number
  hash: string
}

export interface ScanResult {
  root: string
  totalFiles: number
  totalSize: number
  duplicateFileCount: number
  duplicateGroups: Array<DuplicateGroup>
}
