"""create ai_extraction_logs

Revision ID: d3d4e5f80e2c
Revises: 
Create Date: 2026-07-23 16:27:29.873437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d4e5f80e2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_extraction_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claimInvoiceFileId', sa.Integer(), nullable=False),
    sa.Column('pageNumber', sa.Integer(), nullable=True),
    sa.Column('expenseId', sa.Integer(), nullable=True),
    sa.Column('requestedAt', sa.DateTime(), nullable=False),
    sa.Column('respondedAt', sa.DateTime(), nullable=True),
    sa.Column('rawRequestSummary', sa.JSON(), nullable=True),
    sa.Column('rawModelResponse', sa.JSON(), nullable=True),
    sa.Column('suggestedCategoryId', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('redFlagEvaluations', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('errorMessage', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_extraction_logs')
    # ### end Alembic commands ###
